config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'consumers#index'

  devise_for :consumers, controllers: {
    registrations: 'consumers/registrations',
    sessions: 'consumers/sessions',
    passwords: 'consumers/passwords',
    confirmations: 'consumer/confirmations',
    unlocks: 'consumer/unlocks'
    # omniauth_callbacks: 'consumer/omniauth_callbacks'
  }

  # Custom routes for additional consumer actions
  resources :consumers
   
    
  resources :clock_lists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check



end

app/models/clock_list.rb
class ClockList < ApplicationRecord
end

app/controllers/clock_lists_controller.rb
class ClockListsController < ApplicationController
  before_action :set_clock_list, only: %i[ show edit update destroy ]

  # GET /clock_lists or /clock_lists.json
  def index
    @clock_lists = ClockList.all
  end

  # GET /clock_lists/1 or /clock_lists/1.json
  def show
  end

  # GET /clock_lists/new
  def new
    @clock_list = ClockList.new
  end

  # GET /clock_lists/1/edit
  def edit
  end

  # POST /clock_lists or /clock_lists.json
  def create
    @clock_list = ClockList.new(clock_list_params)

    respond_to do |format|
      if @clock_list.save
        format.html { redirect_to clock_list_url(@clock_list), notice: "Clock list was successfully created." }
        format.json { render :show, status: :created, location: @clock_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clock_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clock_lists/1 or /clock_lists/1.json
  def update
    respond_to do |format|
      if @clock_list.update(clock_list_params)
        format.html { redirect_to clock_list_url(@clock_list), notice: "Clock list was successfully updated." }
        format.json { render :show, status: :ok, location: @clock_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clock_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clock_lists/1 or /clock_lists/1.json
  def destroy
    @clock_list.destroy!

    respond_to do |format|
      format.html { redirect_to clock_lists_url, notice: "Clock list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clock_list
      @clock_list = ClockList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clock_list_params
      params.fetch(:clock_list, {})
    end
end

app/helpers/clock_lists_helper.rb
module ClockListsHelper
end

app/views/clock_lists/_clock_list.html.erb
<div id="<%= dom_id clock_list %>">
</div>

app/views/clock_lists/_clock_list.html.haml
%div{:id => "#{dom_id clock_list}"}

app/views/clock_lists/_form.html.erb
<%= form_with(model: clock_list, class: "contents") do |form| %>
  <% if clock_list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(clock_list.errors.count, "error") %> prohibited this clock_list from being saved:</h2>

      <ul>
        <% clock_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/clock_lists/_form.html.haml
= form_with(model: clock_list, class: "contents") do |form|
  - if clock_list.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(clock_list.errors.count, "error")
        prohibited this clock_list from being saved:
      %ul
        - clock_list.errors.each do |error|
          %li= error.full_message
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/clock_lists/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing clock list</h1>

  <%= render "form", clock_list: @clock_list %>

  <%= link_to "Show this clock list", @clock_list, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to clock lists", clock_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clock_lists/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing clock list
  = render "form", clock_list: @clock_list
  = link_to "Show this clock list", @clock_list, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to clock lists", clock_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/clock_lists/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Clock lists" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Clock lists</h1>
    <%= link_to "New clock list", new_clock_list_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="clock_lists" class="min-w-full">
    <% @clock_lists.each do |clock_list| %>
      <%= render clock_list %>
      <p>
        <%= link_to "Show this clock list", clock_list, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/clock_lists/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  - content_for :title, "Clock lists"
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl Clock lists
    = link_to "New clock list", new_clock_list_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #clock_lists.min-w-full
    - @clock_lists.each do |clock_list|
      = render clock_list
      %p
        = link_to "Show this clock list", clock_list, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/clock_lists/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New clock list</h1>

  <%= render "form", clock_list: @clock_list %>

  <%= link_to "Back to clock lists", clock_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clock_lists/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl New clock list
  = render "form", clock_list: @clock_list
  = link_to "Back to clock lists", clock_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/clock_lists/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @clock_list %>

    <%= link_to "Edit this clock list", edit_clock_list_path(@clock_list), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to clock lists", clock_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this clock list", @clock_list, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/clock_lists/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @clock_list
    = link_to "Edit this clock list", edit_clock_list_path(@clock_list), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to "Back to clock lists", clock_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to "Destroy this clock list", @clock_list, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"